/**
 * generate-story-requires.ts
 *
 * Scans src/stories/** for *.stories.{ts,tsx} files and writes
 * .storybook/storybook.requires.ts so Storybook discovers all stories
 * without manual registration.
 *
 * Run: pnpm storybook:gen   (from apps/mobile)
 *      pnpm -C apps/mobile storybook:gen   (from repo root)
 */

import { readdirSync, statSync, writeFileSync } from 'fs';
import { join, relative } from 'path';

const MOBILE_ROOT  = join(__dirname, '..');
const STORIES_ROOT = join(MOBILE_ROOT, 'src', 'stories');
const OUTPUT_FILE  = join(MOBILE_ROOT, '.storybook', 'storybook.requires.ts');

// ── Recursive glob ────────────────────────────────────────────────────────────

function findStories(dir: string): string[] {
  const entries = readdirSync(dir);
  return entries.flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return findStories(full);
    if (/\.stories\.(ts|tsx)$/.test(entry)) return [full];
    return [];
  });
}

// ── Main ──────────────────────────────────────────────────────────────────────

const stories = findStories(STORIES_ROOT).sort();

const requireLines = stories.map((abs) => {
  const rel = relative(join(MOBILE_ROOT, '.storybook'), abs)
    .replace(/\\/g, '/')          // Windows path sep → /
    .replace(/\.tsx?$/, '');      // strip extension (Metro resolves it)
  return `require('${rel}');`;
});

const banner = [
  '// Auto-generated by scripts/generate-story-requires.ts',
  '// Run `pnpm storybook:gen` to refresh after adding new *.stories.tsx files.',
  '// DO NOT edit manually — your changes will be overwritten.',
  '',
].join('\n');

writeFileSync(OUTPUT_FILE, banner + requireLines.join('\n') + '\n');

console.log(`✓ Registered ${stories.length} story file${stories.length !== 1 ? 's' : ''}`);
stories.forEach((s) => console.log('  ', relative(MOBILE_ROOT, s)));
