#!/usr/bin/env tsx
/**
 * Reads apps/mobile/assets/figma/tokens.json and regenerates
 * apps/mobile/src/theme/theme.ts (Tamagui createTheme tokens).
 *
 * Usage: pnpm tokens:sync
 */
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const TOKENS_PATH = path.join(ROOT, 'apps/mobile/assets/figma/tokens.json');
const OUT_PATH = path.join(ROOT, 'apps/mobile/src/theme/generated-tokens.ts');

interface TokenNode {
  value?: string;
  type?: string;
  [key: string]: TokenNode | string | undefined;
}

function resolveRef(value: string, tokens: TokenNode): string {
  const refMatch = value.match(/^\{(.+)\}$/);
  if (!refMatch) return value;
  const parts = refMatch[1].split('.');
  let node: TokenNode | string | undefined = tokens;
  for (const part of parts) {
    if (typeof node === 'object' && node !== null) {
      node = (node as TokenNode)[part];
    } else {
      return value;
    }
  }
  if (typeof node === 'object' && node?.value) {
    return resolveRef(node.value as string, tokens);
  }
  return value;
}

function flattenTokens(
  node: TokenNode,
  prefix: string,
  allTokens: TokenNode,
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, child] of Object.entries(node)) {
    if (child == null) continue;
    const fullKey = prefix ? `${prefix}_${key}` : key;
    if (typeof child === 'object' && child.value !== undefined) {
      result[fullKey] = resolveRef(child.value as string, allTokens);
    } else if (typeof child === 'object') {
      Object.assign(result, flattenTokens(child as TokenNode, fullKey, allTokens));
    }
  }
  return result;
}

function toCamelKey(snakeKey: string): string {
  return snakeKey.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function main() {
  if (!fs.existsSync(TOKENS_PATH)) {
    console.error(`tokens.json not found at ${TOKENS_PATH}`);
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf-8'));
  const global: TokenNode = raw.global ?? raw;

  const flat = flattenTokens(global, '', global);

  const colors: Record<string, string> = {};
  const spacing: Record<string, number> = {};
  const radius: Record<string, number> = {};
  const fontSize: Record<string, number> = {};

  for (const [key, value] of Object.entries(flat)) {
    const camel = toCamelKey(key);
    if (key.startsWith('color_')) {
      colors[camel.replace('color_', '$')] = value;
    } else if (key.startsWith('spacing_')) {
      spacing[camel.replace('spacing_', '$space')] = Number(value);
    } else if (key.startsWith('borderRadius_')) {
      const rk = camel.replace('borderRadius_', '$radius');
      radius[rk] = value === '9999' ? 9999 : Number(value);
    } else if (key.startsWith('fontSize_')) {
      fontSize[camel.replace('fontSize_', '$size')] = Number(value);
    }
  }

  const outDir = path.dirname(OUT_PATH);
  fs.mkdirSync(outDir, { recursive: true });

  const content = `// AUTO-GENERATED by scripts/tokens-sync.ts — do not edit manually
// Source: apps/mobile/assets/figma/tokens.json
// Re-run: pnpm tokens:sync

export const generatedColors = ${JSON.stringify(colors, null, 2)} as const;

export const generatedSpacing = ${JSON.stringify(spacing, null, 2)} as const;

export const generatedRadius = ${JSON.stringify(radius, null, 2)} as const;

export const generatedFontSize = ${JSON.stringify(fontSize, null, 2)} as const;
`;

  fs.writeFileSync(OUT_PATH, content, 'utf-8');
  console.log(`✅  Tokens written to ${OUT_PATH.replace(ROOT + '/', '')}`);
  console.log(`    Colors: ${Object.keys(colors).length}`);
  console.log(`    Spacing: ${Object.keys(spacing).length}`);
  console.log(`    Radius: ${Object.keys(radius).length}`);
  console.log(`    FontSizes: ${Object.keys(fontSize).length}`);
}

main();
